### ISSUE TITLE
Any way to contact you?

### ISSUE THREAD

**Issue by ojmaster** [PoligamerYT/PluginTester#2]
Hey, I use your [Disenchanted Reborn](https://www.spigotmc.org/resources/%E2%9C%A8disenchanted-reborn%E2%9C%A8.99988/) plugin and was really hoping we could talk because I would really like if the plugin could be hooked with [ExcellentEnchants](https://www.spigotmc.org/resources/excellentenchants-pure-vanilla-like-enchantments.61693/)

**Comment by PoligamerYT** [comment]
Write to my discord: PoliZZZ
